port = 8000 
upload_dir = 'web'
hot_reload = True
appname = 'LLM test'
autotest = '*'
#llm = 'host', "http://localhost:1234/v1"
#llm = 'groq', 'llama-3.1-70b-versatile'
llm = 'google', "gemini-2.0-flash"
#llm = 'openai', "gpt-4o"
#llm = 'mistral', "mistral-large-latest"
llm_cache = 'llm.cache'
